from typing import Any, Optional
from pydantic import BaseModel, Field


class OutputGuardrailRequest(BaseModel):
    """Output payload sent to the Output Guardrail Pipeline post LLM execution."""
    response_text: str = Field(..., description="Raw text response generated by the LLM")
    retrieved_context: list[str] = Field(default_factory=list, description="Grounding knowledge context passages retrieved via RAG")
    target_schema: Optional[dict[str, Any]] = Field(default=None, description="Expected JSON Schema or Pydantic schema structure")
    citations: list[str] = Field(default_factory=list, description="Source IDs cited in the response text")
    tool_calls: list[dict[str, Any]] = Field(default_factory=list, description="Execution records of tools invoked during response generation")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Arbitrary response context metadata")
